# Pandas

Материалы:
* Макрушин С.В. "Лекция 2: Библиотека Pandas"
* https://pandas.pydata.org/docs/user_guide/index.html#
* https://pandas.pydata.org/docs/reference/index.html
* Уэс Маккини. Python и анализ данных

## Лабораторная работа №2

### Базовые операции с `DataFrame`

1.1 В файлах `recipes_sample.csv` и `reviews_sample.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца с индексами в таблице `reviews` (безымянный столбец).

In [9]:
import numpy as np
import pandas as pd
recipies = pd.read_csv('recipes_sample.csv') 
recipies['submitted'] = pd.to_datetime(recipies['submitted']) # модификация по заданию 2.1
reviews = pd.read_csv('reviews_sample.csv') 
reviews = reviews.rename(columns={'Unnamed: 0': 'id'})
recipies

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29998,zydeco soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

1.2 Для каждой из таблиц выведите основные параметры:
* количество точек данных (строк);
* количество столбцов;
* тип данных каждого столбца.

In [10]:
len_1 = len(recipies)
len_2 = len(reviews)
num_col_1 = len(recipies.columns)
num_col_2 = len(reviews.columns)
j = 0
j_1 = 0
print(f'Количество точек данных recipies: {len_1}, количество точек данных reviews: {len_2}')
print(f'Количество столбцов recipies: {num_col_1}, количество столбцов reviews: {num_col_2}')
for i in recipies.columns:
    print(f'Тип данных {j} столбца recipies: {recipies[i].dtype}')
    j+=1
for i in reviews.columns:
    print(f'Тип данных {j_1} столбца reviews: {reviews[i].dtype}')
    j_1+=1

Количество точек данных recipies: 30000, количество точек данных reviews: 126696
Количество столбцов recipies: 8, количество столбцов reviews: 6
Тип данных 0 столбца recipies: object
Тип данных 1 столбца recipies: int64
Тип данных 2 столбца recipies: int64
Тип данных 3 столбца recipies: int64
Тип данных 4 столбца recipies: datetime64[ns]
Тип данных 5 столбца recipies: float64
Тип данных 6 столбца recipies: object
Тип данных 7 столбца recipies: float64
Тип данных 0 столбца reviews: int64
Тип данных 1 столбца reviews: int64
Тип данных 2 столбца reviews: int64
Тип данных 3 столбца reviews: object
Тип данных 4 столбца reviews: int64
Тип данных 5 столбца reviews: object

1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [11]:
print('Для recipies:')
for i in recipies.columns:
    if recipies[i].isna().any():
        print(f'В {i} содержатся пропуски')
        print(f'Количество пропусков в {i} = {len(recipies[i].isna()[recipies[i].isna() == True])}')
        print(f'Доля пропусков в {i} = {1-((len(recipies[i]) - len(recipies[i].isna()[recipies[i].isna() == True]))/len(recipies[i]))}')
print('Для reviews:')
for i in reviews.columns:
    if reviews[i].isna().any():
        print(f'В {i} содержатся пропуски')
        print(f'Количество пропусков в {i} = {len(reviews[i].isna()[reviews[i].isna() == True])}')
        print(f'Доля пропусков в {i} = {1-((len(reviews[i]) - len(reviews[i].isna()[reviews[i].isna() == True]))/len(reviews[i]))}')

Для recipies:
В n_steps содержатся пропуски
Количество пропусков в n_steps = 11190
Доля пропусков в n_steps = 0.373
В description содержатся пропуски
Количество пропусков в description = 623
Доля пропусков в description = 0.02076666666666671
В n_ingredients содержатся пропуски
Количество пропусков в n_ingredients = 8880
Доля пропусков в n_ingredients = 0.29600000000000004
Для reviews:
В review содержатся пропуски
Количество пропусков в review = 17
Доля пропусков в review = 0.00013417945317928393

1.4 Рассчитайте среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [12]:
print('Для recipies:')
for i in recipies.columns:
    if recipies[i].dtype == 'int64' or recipies[i].dtype == 'float64':
        print(f'Среднее значение столбца {i} = {np.mean(recipies[i])}')
print('Для reviews:')
for i in reviews.columns:
    if reviews[i].dtype == 'int64' or reviews[i].dtype == 'float64':
        print(f'Среднее значение столбца {i} = {np.mean(reviews[i])}')

Для recipies:
Среднее значение столбца id = 221879.294
Среднее значение столбца minutes = 123.35813333333333
Среднее значение столбца contributor_id = 5635900.5728
Среднее значение столбца n_steps = 9.805582137161085
Среднее значение столбца n_ingredients = 9.008285984848484
Для reviews:
Среднее значение столбца id = 566089.8211466818
Среднее значение столбца user_id = 140801264.7374108
Среднее значение столбца recipe_id = 160094.38706036497
Среднее значение столбца rating = 4.410802235271832

1.5 Создайте серию из 10 случайных названий рецептов.

In [13]:
rand_series = pd.Series(recipies['name'][np.random.randint(len(recipies['name']), size = (10))])
rand_series

14561                             irish omelet
11499                        fried sage leaves
1315     asparagus with herbed cheese on toast
17654                 mike s italian meatballs
24057     shrimp and veggie fettuccini alfredo
16424       low carb hash browns   cauliflower
18610           new mexican potatoes au gratin
11166                        fluffy rice pilaf
5370                 cherries jubillee sundaes
24293            simple swiss steak  crock pot
Name: name, dtype: object

1.6 Измените индекс в таблице `reviews`, пронумеровав строки, начиная с нуля.

In [14]:
reviews_chng = reviews.copy()
reviews_chng['id'] = np.arange(len(reviews['id']))
reviews_chng

,id,user_id,recipe_id,date,rating,review
0,0,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,1,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,2,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,3,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,4,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...,...
126691,126691,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
126692,126692,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
126693,126693,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
126694,126694,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
126695,126695,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.7 Выведите информацию о рецептах, время выполнения которых не больше 20 минут и кол-во ингредиентов в которых не больше 5.

In [15]:
mask_1 = (recipies['minutes'] <= 20) & (recipies['n_ingredients'] <= 5)
table_1 = recipies[mask_1]
table_1

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
28,quick biscuit bread,302399,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
60,peas fit for a king or queen,303944,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
90,hawaiian sunrise mimosa,100837,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
91,tasty dish s banana pudding in 2 minutes,286484,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
94,1 minute meatballs,11361,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0
...,...,...,...,...,...,...,...,...
29873,zip and steam red potatoes with butter and garlic,304922,13,724218,2008-05-27,9.0,"i haven't tried this yet, but i am going to so...",5.0
29874,ziplock vanilla ice cream,74250,10,24386,2003-10-29,8.0,a fun thing for kids to do. may want to use mi...,3.0
29905,zucchini and corn with cheese,256177,15,305531,2007-09-29,4.0,from betty crocker fresh spring recipes. i lik...,5.0
29980,zucchini with jalapeno monterey jack,320622,10,305531,2008-08-20,3.0,simple and yummy!,3.0
29983,zucchini with serrano ham,162411,15,152500,2006-03-31,6.0,"this dish is from tim malzer, a german chef wh...",5.0

### Работа с датами в `pandas`

2.1 Преобразуйте столбец `submitted` из таблицы `recipes` в формат времени. Модифицируйте решение задачи 1.1 так, чтобы считать столбец сразу в нужном формате.

In [30]:
recipies['submitted'] = pd.to_datetime(recipies['submitted'])
recipies.dtypes

name                          object
id                             int64
minutes                        int64
contributor_id                 int64
submitted             datetime64[ns]
n_steps                      float64
description                   object
n_ingredients                float64
description_length           float64
name_word_count                int64
recipe_id                      int64
dtype: object

2.2 Выведите информацию о рецептах, добавленных в датасет не позже 2010 года.

In [31]:
recipies_copy = recipies.copy()
recipies_copy["submitted"] = pd.DatetimeIndex(recipies["submitted"]).year
recipies_copy = recipies_copy[recipies_copy["submitted"] < 2010]
recipies_copy

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count,recipe_id
0,George S At The Cove Black Bean Soup,44123,90,35193,2002,NaN,an original recipe created by chef scott meska...,18.0,330.0,8,44123
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003,NaN,my children and their friends ask for my homem...,NaN,255.0,5,67664
2,I Can T Believe It S Spinach,38798,30,1533,2002,NaN,"these were so go, it surprised even me.",8.0,39.0,7,38798
3,Italian Gut Busters,35173,45,22724,2002,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3,35173
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8,84797
...,...,...,...,...,...,...,...,...,...,...,...
29993,Zuni Caf Zucchini Pickles,316950,2895,62264,2008,NaN,refrigerator pickles for some of the zucchini ...,8.0,298.0,4,316950
29995,Zurie S Holey Rustic Olive And Cheddar Bread,267661,80,200862,2007,16.0,this is based on a french recipe but i changed...,10.0,484.0,8,267661
29996,Zwetschgenkuchen Bavarian Plum Cake,386977,240,177443,2009,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0,4,386977
29997,Zwiebelkuchen Southwest German Onion Cake,103312,75,161745,2004,NaN,this is a traditional late summer early fall s...,NaN,311.0,5,103312
29999,Cookies By Design Cookies On A Stick,298512,29,506822,2008,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0,7,298512

### Работа со строковыми данными в `pandas`

3.1  Добавьте в таблицу `recipes` столбец `description_length`, в котором хранится длина описания рецепта из столбца `description`.

In [18]:
recipies['description_length']  = recipies['description'].str.len()
recipies[500:550]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
500,almond butterscotch latte,314777,5,305531,2008-07-20,3.0,this is from the cookbook cappuccino espresso ...,5.0,98.0
501,almond cake,490199,50,1706426,2012-11-13,NaN,"slightly dense, intensely almond flavored cake",9.0,46.0
502,almond chicken appetizers,143938,35,125640,2005-11-07,NaN,"delicious, crispy chicken nuggets breaded with...",NaN,162.0
503,almond cloud cookies,335824,40,224921,2008-11-08,10.0,this is a recipe for one of king arthur flour'...,6.0,129.0
504,almond coconut joy,316673,10,157425,2008-07-30,NaN,a frozen non-alcoholic drink your family will ...,NaN,143.0
505,almond coffee cheesecake for anna,359713,170,128473,2009-03-08,20.0,this is the perfect choice for a elegant dinne...,NaN,174.0
506,almond coffee creamer mix,198585,5,69474,2006-11-30,NaN,yummy!,NaN,6.0
507,almond cookies,204147,58,317696,2007-01-08,10.0,more italian goodies. passive cook time is pe...,10.0,210.0
508,almond cream cheese glaze,211370,10,58104,2007-02-13,2.0,"this is great on spice cake, carrot cake, bana...",4.0,201.0
509,almond crowned kugel,14613,80,21752,2001-11-20,7.0,my mother used to make this for very special d...,13.0,266.0
510,almond crusted cherry cream pie,265955,90,463498,2007-11-15,7.0,this is my dad's favorite pie. it's pretty eas...,NaN,459.0
511,almond crusted chicken breasts,22337,35,1533,2002-03-14,NaN,NaN,NaN,NaN
512,almond crusted pork with honey dijon dipping s...,386614,28,347233,2009-08-24,10.0,this recipe is one i found on epicurious. it i...,10.0,487.0
513,almond crusted tilapia with caramelized onions...,487671,55,2198343,2012-09-27,NaN,"ready, set, cook! reynolds wrap contest entry...",NaN,193.0
514,almond filled crescent rolls,179011,42,232669,2006-07-24,NaN,these crescents are easy to prepare and it loo...,7.0,124.0
515,almond filo snake,502995,70,1925885,2013-07-04,17.0,sweet and crunchy - and looks great on the pla...,NaN,216.0
516,almond fingers,47545,30,58104,2002-11-24,12.0,a christmas must!!!!! these really need to be ...,9.0,211.0
517,almond flour stevia cookies,519547,28,1489145,2014-11-17,6.0,this is a basic cookie made with real whole fo...,6.0,264.0
518,almond green bean salad,335876,15,92006,2008-11-08,NaN,from a california almonds are in! ad.,8.0,37.0
519,almond horns,179210,37,232669,2006-07-25,22.0,we were eating some almond horns the other eve...,6.0,316.0
520,almond ice cream dairy free,370018,1455,593927,2009-05-06,NaN,zwt7 pacific islands.,5.0,21.0
521,almond joy cake,412006,70,1020526,2010-02-07,NaN,"what a great idea to make with a cake mix, and...",NaN,168.0
522,almond joy drop cookies,136451,28,24386,2005-09-06,NaN,"if you like the candy bar, you will love these...",NaN,127.0
523,almond joy fudge,57757,15,24386,2003-04-03,NaN,no candy thermometer needed for this quick to ...,4.0,157.0
524,almond joy latte,160133,5,8688,2006-03-15,2.0,almond joy candy bar fans will enjoy this warm...,NaN,63.0
525,almond kiss,284868,5,327115,2008-02-07,NaN,yummy nutty hot chocolate.,2.0,26.0
526,almond kowadjik,456968,50,482376,2011-05-22,NaN,this is an african adaption of a dessert made ...,9.0,103.0
527,almond kulfi,136514,250,151325,2005-09-07,7.0,this is a simplified and much quicker way of m...,NaN,493.0
528,almond lemon cake,429293,60,527607,2010-06-10,16.0,"delicious and reasonably low cal, i use splend...",13.0,112.0
529,almond macaroon cake,213177,35,454328,2007-02-22,NaN,this is a simple recipe that produces results ...,6.0,282.0
530,almond meltaways,339697,28,166642,2008-11-27,14.0,these little gems will melt in your mouth! rec...,5.0,140.0
531,almond mocha,247025,5,327115,2007-08-17,4.0,this is wonderful on cool nights. you could a...,NaN,147.0
532,almond paste,15869,15,4470,2001-12-16,5.0,making almond paste is so simple and to me it ...,3.0,81.0
533,almond paste or marzipan,14149,35,10216,2001-11-13,NaN,"marzipan, cover cakes with it, make biscuits w...",9.0,199.0
534,almond peach yogurt bread,80474,65,10113,2004-01-08,NaN,this is a recipe that i found at a bed and bre...,10.0,88.0
535,almond poppy seed pound cake,401584,100,1463218,2009-11-28,12.0,this recipe is very moist and tastes very good...,10.0,146.0
536,almond pudding,482653,95,226863,2012-07-08,NaN,this is a milk pudding that is served in india...,8.0,407.0
537,almond puffs,41990,140,37305,2002-10-02,9.0,this is an interesting change of pace if you l...,8.0,95.0
538,almond raspberry torte,26809,80,25455,2002-04-29,25.0,"this cake is a ""cover girl""--its picture was o...",12.0,386.0
539,almond rhubarb coffee cake,118667,63,1535,2005-04-22,10.0,from my collection of recipes. haven't tried i...,12.0,52.0
540,almond rice casserole,183118,75,290499,2006-08-25,9.0,vegetarian cooking for dummies.,NaN,31.0
541,almond rice custard with berries,115721,25,83400,2005-04-07,12.0,"this creamy rice pudding is yummy, very easy t...",NaN,445.0
542,almond roca cookies,148060,52,37449,2005-12-12,16.0,"this recipe came from lynn scully, rancho sant...",12.0,121.0
543,almond roca gourmet popcorn,407545,20,118840,2010-01-09,NaN,movie night treat from copykat.com.,9.0,35.0
544,almond shortbread,201417,22,235456,2006-12-21,17.0,i love to have this delicious cookie at christ...,7.0,203.0
545,almond sponge cake spain bizcocho de almendras,370125,45,491979,2009-05-06,NaN,posted for zwt,NaN,14.0
546,almond stuffed tofu cubes,15458,45,13063,2001-12-07,8.0,even tofu 'haters' will be intrigued by these ...,NaN,74.0
547,almond toffee crunch,403878,25,1427607,2009-12-15,15.0,this recipe came from a book of wonderful reci...,5.0,260.0
548,almond toffee rugelach,402687,30,6836,2009-12-07,20.0,this is a recipe i came up with on a whim whil...,6.0,279.0
549,almond truffle brownies,160310,35,4439,2006-03-16,19.0,this is from t.o.h. web site and starts with a...,12.0,169.0

3.2 Измените название каждого рецепта в таблице `recipes` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [19]:
recipies['name']  = recipies['name'].str.title()
recipies

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0
...,...,...,...,...,...,...,...,...,...
29995,Zurie S Holey Rustic Olive And Cheddar Bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0
29996,Zwetschgenkuchen Bavarian Plum Cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0
29997,Zwiebelkuchen Southwest German Onion Cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0
29998,Zydeco Soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0
29999,Cookies By Design Cookies On A Stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0

3.3 Добавьте в таблицу `recipes` столбец `name_word_count`, в котором хранится количество слов из названии рецепта (считайте, что слова в названии разделяются только пробелами). Обратите внимание, что между словами может располагаться несколько пробелов подряд.

In [20]:
recipies['name_word_count']=(recipies['name']).str.split().str.len()
recipies.to_csv('3_3_pandas.csv')
recipies

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8
...,...,...,...,...,...,...,...,...,...,...
29995,Zurie S Holey Rustic Olive And Cheddar Bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0,484.0,8
29996,Zwetschgenkuchen Bavarian Plum Cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0,286.0,4
29997,Zwiebelkuchen Southwest German Onion Cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN,311.0,5
29998,Zydeco Soup,486161,60,227978,2012-08-29,NaN,this is a delicious soup that i originally fou...,NaN,648.0,2
29999,Cookies By Design Cookies On A Stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0,125.0,7

### Группировки таблиц `pd.DataFrame`

4.1 Посчитайте количество рецептов, представленных каждым из участников (`contributor_id`). Какой участник добавил максимальное кол-во рецептов?

In [21]:
file4_1=pd.DataFrame(recipies['contributor_id'].value_counts())
s=pd.DataFrame(file4_1)
print(f'{s}\n\n{s.iloc[0].name}\n')

         contributor_id
89831               421
37449               346
37779               345
1533                186
169430              183
...                 ...
1061628               1
1076183               1
429061                1
64032                 1
186118                1

[8404 rows x 1 columns]

89831

4.2 Посчитайте средний рейтинг к каждому из рецептов. Для скольких рецептов отсутствуют отзывы? Обратите внимание, что отзыв с нулевым рейтингом или не заполненным текстовым описанием не считается отсутствующим.

In [22]:
file4_2=pd.DataFrame(reviews['recipe_id'].value_counts())
file4_2

        recipe_id
27208        1382
82102         708
135350        674
107786        592
50719         486
...           ...
23964           1
499966          1
418761          1
430164          1
296868          1

[28100 rows x 1 columns]

4.3 Посчитайте количество рецептов с разбивкой по годам создания.

In [23]:
d4_3=pd.DatetimeIndex(recipies['submitted']).year
d4_3=pd.Series(d4_3)
d4_3.value_counts()

2007    4429
2008    4029
2006    3473
2005    3130
2009    2963
2002    2644
2003    2334
2004    2153
2010    1538
2011     922
2012     659
2001     589
2013     490
1999     275
2014     139
2000     104
2015      42
2017      39
2016      24
2018      24
Name: submitted, dtype: int64

### Объединение таблиц `pd.DataFrame`

5.1 При помощи объединения таблиц, создайте `DataFrame`, состоящий из четырех столбцов: `id`, `name`, `user_id`, `rating`. Рецепты, на которые не оставлен ни один отзыв, должны отсутствовать в полученной таблице. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и попытавшись найти строку, соответствующую этому рецепту, в полученном `DataFrame`.

In [24]:
reviews['id']=reviews['recipe_id']
df5_1 = pd.merge(recipies, reviews) 
df5_1=df5_1[['id','name','user_id','rating']]
df5_1

            id                                    name  user_id  rating
0        44123   George S At The Cove  Black Bean Soup   743566       5
1        44123   George S At The Cove  Black Bean Soup    76503       5
2        44123   George S At The Cove  Black Bean Soup    34206       5
3        67664      Healthy For Them  Yogurt Popsicles   494084       5
4        67664      Healthy For Them  Yogurt Popsicles   303445       5
...        ...                                     ...      ...     ...
126691  486161                             Zydeco Soup   305531       5
126692  486161                             Zydeco Soup  1271506       5
126693  486161                             Zydeco Soup   724631       5
126694  486161                             Zydeco Soup   133174       5
126695  298512  Cookies By Design   Cookies On A Stick   804234       1

[126696 rows x 4 columns]

5.2 При помощи объединения таблиц и группировок, создайте `DataFrame`, состоящий из трех столбцов: `recipe_id`, `name`, `review_count`, где столбец `review_count` содержит кол-во отзывов, оставленных на рецепт `recipe_id`. У рецептов, на которые не оставлен ни один отзыв, в столбце `review_count` должен быть указан 0. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и найдя строку, соответствующую этому рецепту, в полученном `DataFrame`.

In [25]:
a=pd.DataFrame(reviews['recipe_id'].value_counts())
a['id']=a.index
a.index=[[i for i in range(a.shape[0])]]
a.columns = ['review_count','id']
df5_2=pd.merge(a,reviews)
df5_2=pd.merge(df5_2,recipies)
df5_2=df5_2[['recipe_id', 'name', 'review_count']]
recipies['recipe_id']=recipies['id']
s2=pd.merge(recipies,reviews,how='outer')
s2=s2[s2['rating'].isna()]
df5_2=pd.merge(df5_2,s2,how='outer')
df5_2=df5_2[['review_count', 'name', 'recipe_id']]
df5_2['review_count']=df5_2['review_count'].fillna(0)
df5_2

        review_count                                  name  recipe_id
0             1382.0            To Die For Crock Pot Roast      27208
1             1382.0            To Die For Crock Pot Roast      27208
2             1382.0            To Die For Crock Pot Roast      27208
3             1382.0            To Die For Crock Pot Roast      27208
4             1382.0            To Die For Crock Pot Roast      27208
...              ...                                   ...        ...
128591           0.0                    Zingy Potato Salad      66966
128592           0.0    Zucchini  Mock Green Papaya  Salad     249846
128593           0.0         Zucchini And Corn With Cheese     256177
128594           0.0                    Zucchini Nut Salad     178243
128595           0.0  Zucchini With Bell Pepper And Tomato     363362

[128596 rows x 3 columns]

5.3. Выясните, рецепты, добавленные в каком году, имеют наименьший средний рейтинг?

In [26]:
reviews[reviews['id']==66]['rating'].sum()

89

### Сохранение таблиц `pd.DataFrame`

6.1 Отсортируйте таблицу в порядке убывания величины столбца `name_word_count` и сохраните результаты выполнения заданий 3.1-3.3 в csv файл.

In [27]:
recipies6_1=recipies.sort_values('name_word_count',ascending=False)
recipies6_1

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count,recipe_id
26223,Subru Uncle S Whole Green Moong Dal I Ll Be Ma...,77188,95,6357,2003-11-21,NaN,my dad and mom quite enjoy this lentil curry. ...,15.0,343.0,15,77188
28083,Tsr Version Of T G I Friday S Black Bean Soup...,102274,75,74652,2004-10-19,9.0,from www.topsecretrecipes.com i got this copyc...,16.0,436.0,14,102274
26222,Subru Uncle S Toor Ki Dal Sindhi Style Dad M...,76908,65,6357,2003-11-18,29.0,this is the lentil curry that subru uncle(our ...,15.0,1087.0,14,76908
27876,Top Secret Recipes Version Of I H O P Griddl...,113346,20,175727,2005-03-14,5.0,this recipe is top secret recipes version of i...,9.0,129.0,14,113346
5734,Chicken Curry Or Cat S Vomit On A Bed Of Magg...,294898,30,802799,2008-03-28,11.0,an old family recipe that's easy to make since...,12.0,144.0,13,294898
...,...,...,...,...,...,...,...,...,...,...,...
3253,Blackmoons,323195,430,415934,2008-09-04,5.0,my mom was a newlywed in the 1950s when she fo...,NaN,389.0,1,323195
4138,Bushwhacker,156521,10,177392,2006-02-17,1.0,this drink is an excellent after dinner drink ...,6.0,124.0,1,156521
2357,Basbousa,12957,60,18391,2001-10-20,NaN,this is a traditional middle eastern dessert. ...,NaN,78.0,1,12957
15052,Josefinas,264859,20,498271,2007-11-11,7.0,"from the junior league of corpus christi tx, t...",NaN,92.0,1,264859
4710,Caramels,143615,30,212088,2005-11-02,NaN,i've been making these at christmas time for y...,6.0,341.0,1,143615

6.2 Воспользовавшись `pd.ExcelWriter`, cохраните результаты 5.1 и 5.2 в файл: на лист с названием `Рецепты с оценками` сохраните результаты выполнения 5.1; на лист с названием `Количество отзывов по рецептам` сохраните результаты выполнения 5.2.